shrine {

  shrineHubBaseUrl = "https://shrine-hub.faraway.com:6443" //The shrine hub's URL as observed from this tomcat server
  i2b2BaseUrl = "http://i2b2.example.com:9090" //The local i2b2's URL as observed from this tomcat server
  i2b2Domain = "exampleDomain"
  i2b2ShrineProjectName = "SHRINE"

  nodeKey = "testNode" //node key to get information from the hub about this node.

  //shrineDatabaseType = "mysql" // "mysql" by default. It can be "sqlserver" "mysql" or "oracle"

  webclient {
   siteAdminEmail = "shrine-admin@example.com"
  }
  
  hiveCredentials {
    username = "demo"
    crcProjectId = "Demo"
  }//hiveCredentials
}//shrine
