<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<name>SHRINE QEP Service</name>
	<artifactId>shrine-qep</artifactId>
	<packaging>jar</packaging>
	<parent>
		<groupId>net.shrine</groupId>
		<artifactId>shrine-base</artifactId>
		<version>4.4.0</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>
	<build>
		<sourceDirectory>src/main/scala</sourceDirectory>
		<testSourceDirectory>src/test/scala</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>scala-maven-plugin</artifactId>
				<configuration>
					<useTestClasspath>false</useTestClasspath>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>net.shrine</groupId>
			<artifactId>shrine-auth</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.shrine</groupId>
			<artifactId>shrine-hub-service</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.shrine</groupId>
			<artifactId>shrine-protocol</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.slick</groupId>
			<artifactId>slick_${scala-major-version}</artifactId>
			<version>${slick-version}</version>
		</dependency>
		<dependency>
			<groupId>io.circe</groupId>
			<artifactId>circe-config_${scala-major-version}</artifactId>
			<version>${circe-config-version}</version>
		</dependency>
		<dependency>
			<groupId>net.shrine</groupId>
			<artifactId>shrine-ontology-service</artifactId>
			<version>${project.version}</version>
		</dependency>
		<!-- Test Scoped dependencies -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>${h2-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.shrine</groupId>
			<artifactId>shrine-util</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.shrine</groupId>
			<artifactId>shrine-protocol</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
