shrine {
  authenticate {
    usersource
      {
        type = "PmUserSource" //Must be ConfigUserSource (for isolated testing) or PmUserSource (for everything else)
      }
    //pmProjectName = "ACT" to restrict shrine use to just one project. Leave blank to ignore
  }
  pmEndpoint {
    timeout = "10 seconds"
    urlPath = "/i2b2/services/PMService/getServices"
    concurrentLimit = "3" //i2b2 can handle only (cores * 16 -1) simultaneious requests, so budget accordingly
    retryDelay = "250 milliseconds"
    tls.trustManager = "TrustAllCerts" // Should be "VerifyServerCerts", but can be "TrustAllCerts" to allow man-in-the-middle attacks
  }

  qep {
    authenticationType = "pm"
  }
}