<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <name>SHRINE MessageQueueService</name>
    <artifactId>shrine-message-service</artifactId>
    <packaging>jar</packaging>
    <parent>
        <groupId>net.shrine</groupId>
        <artifactId>shrine-base</artifactId>
        <version>4.4.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <build>
        <sourceDirectory>src/main/scala</sourceDirectory>
        <testSourceDirectory>src/test/scala</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-util</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-protocol</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-hub-data-store</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.http4s</groupId>
            <artifactId>http4s-dsl_${scala-major-version}</artifactId>
            <version>${http4s-version}</version>
        </dependency>
        <dependency>
            <groupId>io.circe</groupId>
            <artifactId>circe-generic-extras_${scala-major-version}</artifactId>
            <version>${circe-extras-version}</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${servlet-api-version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>iam</artifactId>
            <version>${awssdk-version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.laserdisc/fs2-aws-core -->
        <dependency>
            <groupId>io.laserdisc</groupId>
            <artifactId>fs2-aws-sqs_${scala-major-version}</artifactId>
            <version>${fs2-aws-version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.fd4s</groupId>
            <artifactId>fs2-kafka_${scala-major-version}</artifactId>
            <version>${fs2-kafka-version}</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2-version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
