BEGIN
    CREATE OR REPLACE DATABASE I2B2_SHRINE_MU;
    USE DATABASE I2B2_SHRINE_MU;
    
    CREATE SCHEMA I2B2DATA;
    CREATE SCHEMA I2B2METADATA;
    CREATE SCHEMA I2B2HIVE;
    CREATE SCHEMA I2B2PM;
    CREATE SCHEMA I2B2WORKDATA;
END;


BEGIN
    CREATE OR REPLACE DATABASE I2B2_SHRINE_WASHU;
    USE DATABASE I2B2_SHRINE_WASHU;
    
    CREATE SCHEMA I2B2DATA;
    CREATE SCHEMA I2B2METADATA;
    CREATE SCHEMA I2B2HIVE;
    CREATE SCHEMA I2B2PM;
    CREATE SCHEMA I2B2WORKDATA;
END;