<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>net.shrine</groupId>
        <artifactId>shrine-base</artifactId>
        <version>${revision}${sha1}${changelist}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>docker</artifactId>
    <name>SHRINE Docker Network</name>
    <packaging>pom</packaging>

    <properties>
        <SHRINE_VERSION>${project.version}</SHRINE_VERSION>
        <DOCKER_REGISTRY_URL>localhost:5000</DOCKER_REGISTRY_URL>
        <SHRINE_MYSQL_REPO_NAME>${DOCKER_REGISTRY_URL}/shrine-mysql:${SHRINE_VERSION}</SHRINE_MYSQL_REPO_NAME>
        <SHRINE_CERTS_REPO_NAME>${DOCKER_REGISTRY_URL}/shrine-certs:${SHRINE_VERSION}</SHRINE_CERTS_REPO_NAME>
        <SHRINE_NODE_REPO_NAME>${DOCKER_REGISTRY_URL}/shrine-node:${SHRINE_VERSION}</SHRINE_NODE_REPO_NAME>
        <KAFKA_REPO_NAME>${DOCKER_REGISTRY_URL}/kafka:${SHRINE_VERSION}</KAFKA_REPO_NAME>
        <KAFKA_VERSION>3.4.1</KAFKA_VERSION>
        <SHRINE_I2B2_WILDFLY_REPO_NAME>${DOCKER_REGISTRY_URL}/shrine-i2b2-wildfly:${SHRINE_VERSION}</SHRINE_I2B2_WILDFLY_REPO_NAME>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <id>Load environment variables from file</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-shrine-mysql</id>
                        <phase>buildShrineMySQL</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-shrine-certs</id>
                        <phase>buildShrineCerts</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-shrine-wildfly</id>
                        <phase>buildShrineI2b2Wildfly</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-shrine-node</id>
                        <phase>buildShrineNode</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-shrine-mysql</id>
                        <phase>pushShrineMySQL</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-shrine-certs</id>
                        <phase>pushShrineCerts</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-shrine-wildfly</id>
                        <phase>pushShrineI2b2Wildfly</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-shrine-node</id>
                        <phase>pushShrineNode</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>create-registry</id>
                        <phase>createRegistry</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>start-registry</id>
                        <phase>startRegistry</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-registry</id>
                        <phase>stopRegistry</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>start-network</id>
                        <phase>startNetwork</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-network</id>
                        <phase>stopNetwork</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${project.basedir}/src/main/docker/.env</file>
                            </files>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <groupId>org.codehaus.mojo</groupId>
                <executions>
                    <execution>
                        <id>Create registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>createRegistry</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>run</argument>
                                <argument>-d</argument>
                                <argument>-p</argument>
                                <argument>5000:5000</argument>
                                <argument>--name</argument>
                                <argument>shrine-images-registry</argument>
                                <argument>registry:latest</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Start SHRINE registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>startRegistry</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>container</argument>
                                <argument>restart</argument>
                                <argument>shrine-images-registry</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Stop SHRINE registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>stopRegistry</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>container</argument>
                                <argument>stop</argument>
                                <argument>shrine-images-registry</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Build SHRINE mysql container</id>
                        <phase>buildShrineMySQL</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>build</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/images/mysql/Dockerfile</argument>
                                <argument>--tag</argument>
                                <argument>${SHRINE_MYSQL_REPO_NAME}</argument>
                                <argument>--no-cache</argument>
                                <argument>../../</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Build SHRINE certs container</id>
                        <phase>buildShrineCerts</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>build</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/images/certs/Dockerfile</argument>
                                <argument>--tag</argument>
                                <argument>${SHRINE_CERTS_REPO_NAME}</argument>
                                <argument>--progress</argument>
                                <argument>plain</argument>
                                <argument>--no-cache</argument>
                                <argument>../../</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Build SHRINE i2b2 wildfly container</id>
                        <phase>buildShrineI2b2Wildfly</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>build</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/images/i2b2/Dockerfile</argument>
                                <argument>--build-arg</argument>
                                <argument>I2B2_WILDFLY_TAG=${I2B2_WILDFLY_TAG}</argument>
                                <argument>--tag</argument>
                                <argument>${SHRINE_I2B2_WILDFLY_REPO_NAME}</argument>
                                <argument>--no-cache</argument>
                                <argument>../../</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Build Kafka container</id>
                        <phase>buildKafka</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>build</argument>
                                <argument>--no-cache</argument>
                                <argument>--build-arg</argument>
                                <argument>SCALA_VERSION=${scala-major-version}</argument>
                                <argument>--build-arg</argument>
                                <argument>KAFKA_VERSION=${KAFKA_VERSION}</argument>
                                <argument>--tag</argument>
                                <argument>${KAFKA_REPO_NAME}</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/images/kafka/Dockerfile</argument>
                                <argument>../../</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Build SHRINE node container</id>
                        <phase>buildShrineNode</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>build</argument>
                                <argument>--no-cache</argument>
                                <argument>--build-arg</argument>
                                <argument>SHRINE_VERSION=${SHRINE_VERSION}</argument>
                                <argument>--tag</argument>
                                <argument>${SHRINE_NODE_REPO_NAME}</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/images/shrine-node/Dockerfile</argument>
                                <argument>../../</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>Push SHRINE mysql image to docker registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>pushShrineMySQL</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>push</argument>
                                <argument>${SHRINE_MYSQL_REPO_NAME}</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Push SHRINE certs image to docker registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>pushShrineCerts</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>push</argument>
                                <argument>${SHRINE_CERTS_REPO_NAME}</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Push SHRINE i2b2 wildfly image to docker registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>pushShrineI2b2Wildfly</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>push</argument>
                                <argument>${SHRINE_I2B2_WILDFLY_REPO_NAME}</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Push SHRINE node image to docker registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>pushShrineNode</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>push</argument>
                                <argument>${SHRINE_NODE_REPO_NAME}</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Push Kafka image to docker registry at ${DOCKER_REGISTRY_URL}</id>
                        <phase>pushKafka</phase>
                        <configuration>
                            <executable>docker</executable>
                            <arguments>
                                <argument>push</argument>
                                <argument>${KAFKA_REPO_NAME}</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Start SHRINE Network</id>
                        <phase>startNetwork</phase>
                        <configuration>
                            <executable>docker-compose</executable>
                            <environmentVariables>
                                <KAFKA_REPO_NAME>${KAFKA_REPO_NAME}</KAFKA_REPO_NAME>
                                <SHRINE_VERSION>${SHRINE_VERSION}</SHRINE_VERSION>
                                <DOCKER_REGISTRY_URL>${DOCKER_REGISTRY_URL}/</DOCKER_REGISTRY_URL>
                            </environmentVariables>
                            <arguments>
                                <argument>--env-file</argument>
                                <argument>src/main/docker/.env</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/certs/docker-compose.yml</argument>
<!--                                <argument>-f</argument>-->
<!--                                <argument>src/main/docker/dev-environments/kafka/docker-compose.yml</argument>-->
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/shrine-hub/docker-compose.yml</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/shrine-node1/docker-compose.yml</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/shrine-node2/docker-compose.yml</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/docker-compose.yml</argument>
                                <argument>up</argument>
                                <argument>--detach</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Stop SHRINE Network</id>
                        <phase>stopNetwork</phase>
                        <configuration>
                            <executable>docker-compose</executable>
                            <environmentVariables>
                                <SHRINE_VERSION>${SHRINE_VERSION}</SHRINE_VERSION>
                                <KAFKA_REPO_NAME>${KAFKA_REPO_NAME}</KAFKA_REPO_NAME>
                                <DOCKER_REGISTRY_URL>${DOCKER_REGISTRY_URL}/</DOCKER_REGISTRY_URL>
                            </environmentVariables>
                            <arguments>
                                <argument>--env-file</argument>
                                <argument>src/main/docker/.env</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/certs/docker-compose.yml</argument>
<!--                                <argument>-f</argument>-->
<!--                                <argument>src/main/docker/dev-environments/kafka/docker-compose.yml</argument>-->
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/shrine-hub/docker-compose.yml</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/shrine-node1/docker-compose.yml</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/shrine-node2/docker-compose.yml</argument>
                                <argument>-f</argument>
                                <argument>src/main/docker/dev-environments/docker-compose.yml</argument>
                                <argument>down</argument>
                            </arguments>
                        </configuration>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.shrine.maven.plugin</groupId>
                <artifactId>shrine-docker-custom-lifecycle-plugin</artifactId>
                <version>${project.version}</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
</project>