shrine {
  adapter {
    adapterMappingsFileName = "AdapterMappings.csv"

    create = true

    crcEndpoint {
      urlPath = /i2b2/services/QueryToolService
      timeout = "45 seconds"
      concurrentLimit = "9" //i2b2 can handle only (cores * 16 -1) simultaneious requests, so budget accordingly. Respect competition for other users including PM authentication
      retryDelay = "250 milliseconds"
      tls.trustManager = "TrustAllCerts" // Should be "VerifyServerCerts", but can be "TrustAllCerts" to allow man-in-the-middle attacks
    }

    crcRunQueryTimeLimit = "30 seconds" //time limit set in requests to the CRC to run a query
    queuedQueryTimeToLive = "4 days" //time limit to request responces for CRC QUEUED queries before giving up
    queuedQueryPollInterval = "60 seconds" //time between polling the CRC for QUEUED queries
    queuedQueryRestTimeBeforePolling = "15 seconds" //time before polling the CRC for a QUEUED query after it is first reported as QUEUED
    queuedQueryCrcPollHttpCallTimeout = "30 seconds" //time allowed for the CRC to reply when polled for a QUEUED query

    setSizeObfuscation = true
    immediatelyRunIncomingQueries = true
    adapterMappingsInsertStatement = "INSERT INTO ADAPTER_MAPPING (SHRINE_KEY, ADAPTER_KEY) VALUES (?, ?)"

    obfuscation {
      binSize = 1 //Round to the nearest binSize. Use 1 for no effect (to match SHRINE 1.21 and earlier).
      sigma = 1.33 //Noise to inject. Use 0 for no effect. (Use 1.33 to match SHRINE 1.21 and earlier).
      clamp = 3 //Maximum amount of noise to inject. (Use 3 to match SHRINE 1.21 and earlier).
      lowLimit = 3 //Anything below this will be reported as "lowLimit or fewer"
    }

    botDefense {
      countsAndMilliseconds = [
        {count = 200, milliseconds = 36000000} //allow up to 200 queries in 10 hours
//        {count = 2000000, milliseconds = 3600000} //allow for a lot more during scale-up testing
      ]
    }

    query {
      database {
//        dataSourceFrom = "JNDI" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests, JNDI everywhere else
//        jndiDataSourceName = "java:comp/env/jdbc/adapter" //or leave out for tests
        //slickProfileClassName = "slick.jdbc.MySQLProfile$" // Can be
        //        slick.jdbc.H2Profile$
        //        slick.jdbc.MySQLProfile$
        //        slick.jdbc.PostgresProfile$
        //        slick.jdbc.SQLServerProfile$
        //        slick.jdbc.JdbcProfile
        //        slick.jdbc.OracleProfile$
        //        slick.jdbc.SQLServerProfile$
        //
        //        (Yes, with the $ on the end)
        // but will be inferred to a reasonable default via shrine's shrine.shrineDatabaseType property


        // For testing without JNDI
        //      dataSourceConfig {

        //typical test settings for unit tests
        //driverClassName = "org.h2.Driver"

        //url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;" //H2 embedded in-memory for unit tests
        //url = "jdbc:h2:~/stewardTest.h2;MODE=MySQL;" //H2 embedded on disk at ~/test
        //      }
        timeout = "30 seconds" //time to wait before db gives up, in seconds.
//        createTablesOnStart = false //for testing with H2 in memory, when not running unit tests. Set to false normally
      }
    }
  }
}