ServerName https://shrine-dev.nextgenbmi.umsystem.edu

ProxyIOBufferSize 65536
ProxyPass "/shrine-api/" "ajp://localhost:8010/shrine-api/"


# ## hits to just the bare hostname should go to landing page
<LocationMatch "^/$">
  RewriteEngine On
  RewriteRule .* /shrine-api/shrine-webclient
</LocationMatch>


# <LocationMatch "/shrine-api/(staticData|ontology|qep|steward|shrine-webclient)">
 
#   AuthType shibboleth
#   ShibRequestSetting requireSession 1
#   Require valid-user local
  
#   ShibUseEnvironment On
#   ShibUseHeaders On
#   # no caching
#   Header set Cache-Control "no-cache, no-store, must-revalidate"
#   Header set Pragma "no-cache"
#   Header set Expires 0
  
#   # CORS / Access-Control
#   ## ADJUST_FOR_YOUR_SITE:
#   # shib-idp.umsystem.edu

#   Header set Access-Control-Allow-Origin *
  
  
#   # isSsoMode cookie
#   Header set Set-Cookie isSsoMode=true
 
#   </LocationMatch>