version: '3.5'

services:
  kafka-certs:
    container_name: kafka-certs
    image: ${DOCKER_REGISTRY_URL}shrine-certs:${SHRINE_VERSION}
    command: ["/tmp/setup_shrine_keystore.sh", "kafka-1", "kafka-2"]
    volumes:
      - shrine-kafka-truststore-vol:/usr/local/shrine/conf/shrine-keystores

  kafka-1:
    image: ${KAFKA_REPO_NAME}
    container_name: kafka-1
    depends_on:

      - kafka-certs
    environment:
      KAFKA_HOSTNAME: kafka-1
      BROKER_ID: 1
      BROKER_PORT: 9092
      CONTROLLER_PORT: 29092
      CONTROLLER1_PORT: 29092
      CONTROLLER2_PORT: 29093
      CONTROLLER3_PORT: 29094
    ports:
      - '29092:29092'
    volumes:
      - shrine-kafka-truststore-vol:/usr/local/kafka/truststore:ro
    networks:
      - i2b2-net
      - kafka-net

  kafka-2:
    image: ${KAFKA_REPO_NAME}
    container_name: kafka-2
    depends_on:
      - kafka-certs
    environment:
      KAFKA_HOSTNAME: kafka-2
      BROKER_ID: 2
      BROKER_PORT: 9093
      CONTROLLER_PORT: 29093
      CONTROLLER1_PORT: 29092
      CONTROLLER2_PORT: 29093
      CONTROLLER3_PORT: 29094
    ports:
      - '29093:29093'
    volumes:
      - shrine-kafka-truststore-vol:/usr/local/kafka/truststore:ro
    networks:
      - i2b2-net
      - kafka-net

  kafka-3:
    image: ${KAFKA_REPO_NAME}
    container_name: kafka-3
    depends_on:
      - kafka-certs
    environment:
      KAFKA_HOSTNAME: kafka-3
      BROKER_ID: 3
      BROKER_PORT: 9094
      CONTROLLER_PORT: 29094
      CONTROLLER1_PORT: 29092
      CONTROLLER2_PORT: 29093
      CONTROLLER3_PORT: 29094
    ports:
      - '29094:29094'
    volumes:
      - shrine-kafka-truststore-vol:/usr/local/kafka/truststore:ro
    networks:
      - i2b2-net
      - kafka-net
volumes:
    shrine-kafka-truststore-vol: