shrine {

  shrineHubBaseUrl = "https://your.hub.base.url:6443"
  i2b2BaseUrl = "http://your.i2b2.base.url:9090"
  i2b2Domain = "youri2b2domain"
  i2b2ShrineProjectName = "SHRINE"

  nodeKey = "your-node-key"

  hiveCredentials {
    username = "demo"
    crcProjectId = "ACT"
  }

  adapter {
    query {
      database {
        dataSourceConfig {
          url = "jdbc:h2:./shrine-adapter-exec/databases/ADAPTER.h2;MODE=MySQL;"
        }
        createTablesOnStart = true
      }

    }
  }
}