#!/bin/bash
# replace image names and arguments

docker build  \
--platform=linux/amd64 \
-t 063312575449.dkr.ecr.us-east-2.amazonaws.com/shrine-server:mu \
--build-arg ENVIRONMENT=prod \
--build-arg PROJECT=mu \
--no-cache .



# docker build  \
# --platform=linux/amd64 \
# -t 063312575449.dkr.ecr.us-east-2.amazonaws.com/shrine-server:washu \
# --build-arg ENVIRONMENT=prod \
# --build-arg PROJECT=washu \
# --no-cache .