#!/bin/bash
# replace image names and arguments

# docker build  \
# --platform=linux/amd64 \
# -t 500206249851.dkr.ecr.us-east-2.amazonaws.com/shrine-server:mu \
# --build-arg ENVIRONMENT=dev \
# --build-arg PROJECT=mu \
# --no-cache .



docker build  \
--platform=linux/amd64 \
-t 500206249851.dkr.ecr.us-east-2.amazonaws.com/shrine-server:washu \
--build-arg ENVIRONMENT=dev \
--build-arg PROJECT=washu \
--no-cache .