#!/bin/bash


docker run \
--platform=linux/amd64 \
--read-only=true \
-p 6060:6060 \
500206249851.dkr.ecr.us-east-2.amazonaws.com/shrine-server:mu


# docker run \
# --platform=linux/amd64 \
# --read-only=true \
# -p 6060:6060 \
# 500206249851.dkr.ecr.us-east-2.amazonaws.com/shrine-server:washu
