version: '3.8'

services:

  i2b2-web:
    image: i2b2-web:latest
    build:
      context: ./i2b2-web
      args:
        - CLIENT_TYPE=${CLIENT_TYPE}
        - SERVER_NAME=${SERVER_NAME}
        - SERVER_PATH=${SERVER_PATH}
    container_name: i2b2-web
    ports:
      - "80:80"
    networks:
      - i2b2-net
    depends_on:
      - i2b2-wildfly

  i2b2-wildfly:
    # platform: linux/amd64
    image: i2b2-wildfly:latest
    build:
      context: ./i2b2-server
      args:
        - ENVIRONMENT=dev
    container_name: i2b2-wildfly
    ports:
      - "8009:8009"
      - "8080:8080"
      - "9990:9990"
    networks:
      - i2b2-net

networks:
  i2b2-net:
    name: i2b2-net
