<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>shrine-base</artifactId>
        <groupId>net.shrine</groupId>
        <version>4.4.0</version>
        <relativePath>/../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>shrine-api-war</artifactId>
    <name>SHRINE API War</name>
    <packaging>war</packaging>
    <build>
     <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-war-plugin</artifactId>
            <configuration>
                <webResources>
                    <resource>
                        <directory>../../qep/frontend/dist</directory>
                        <targetPath>shrine-webclient</targetPath>
                    </resource>
                </webResources>
            </configuration>
        </plugin>
     </plugins>
    </build>
    <dependencies>
        <!-- For some reason scalatest's dependency on an old version of scala-xml is taking precedence over the version
        in shrine-api-app - despite this subproject's lack of tests. Adding it here forces the right version. -->
        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-xml_${scala-major-version}</artifactId>
            <version>${scala-xml-version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-api-app</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-qep-frontend</artifactId>
            <version>${project.version}</version>
            <type>pom</type>
        </dependency>
    </dependencies>
</project>
