version: '3.5'

services:

  shrine-certs:
    container_name: shrine-certs
    image: ${DOCKER_REGISTRY_URL}shrine-certs:${SHRINE_VERSION}
    command: ["/tmp/setup_shrine_keystore.sh", "shrine-hub", "shrine-node1", "shrine-node2"]
    volumes:
      - shrine-keystore-vol:/usr/local/shrine/conf/shrine-keystores/
    networks:
      - shrine-certs-net











