shrine {
    network {
        network {
            name = "Shrine Docker Test Network" //Name of your network
            hubQueueName = "hub" //queue used to send messages to the hub, different from the queue used to send messages to a QEP and an adapter colocated with the hub
            adminEmail = "yourname@example.com",
            momId = "shrineHubUser"
//             kafka = {
//               networkPrefix = "dockerTestNetwork"
//               bootstrapServers = "kafka-1:9092,kafka-2:9093,kafka-3:9094"
//               securityProtocol = "SASL_PLAINTEXT"
//               securityMechanism = "PLAIN"
//             }
        }
        nodes = [
            {
              name = "Local Dev Hub"
              key = "shrine-hub"
              userDomainName = "shrine-dockerHub"
              queueName = "shrine-hub"
              sendQueries = "false"
              adminEmail = ""
              momId = "shrineHubUser"
            },
            {
              name = "Local Node 1"
              key = "shrine-node1"
              userDomainName = "shrine-dockerNode01"
              queueName = "shrine-node1"
              sendQueries = "true"
              adminEmail = ""
              momId = "shrineNode1User"
            },
            {
                name = "Local Node 2"
                key = "shrine-node2"
                userDomainName = "shrine-dockerNode02"
                queueName = "shrine-node2"
                sendQueries = "true"
                adminEmail = ""
                momId = "shrineNode2User"
            }
        ]
    }
}