shrine {
  queryEntryPoint{
    audit {
      database {
        dataSourceFrom = "dataSourceConfig" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests and command line tools, JNDI everywhere else
        dataSourceConfig {
          driverClassName = "com.mysql.cj.jdbc.Driver" //JDBC driver class name
          url = "jdbc:mysql://shrinedb:3306/HUB?serverTimezone=UTC" //URL to your database
          credentials {
            username = "root"
            password = "password"
          }
        }
      }
    }
  }
  hub {
      create = true
      messagequeue {
        blockingqWebApi {
          enabled = false //todo remove when we have this disabled by default in our test systems
        }
      }
      database {
          dataSourceFrom = "dataSourceConfig" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests and command line tools, JNDI everywhere else
          dataSourceConfig {
            driverClassName = "com.mysql.cj.jdbc.Driver" //JDBC driver class name
            url = "jdbc:mysql://shrinedb:3306/HUB?serverTimezone=UTC" //URL to your database
            credentials {
              username = "root"
              password = "password"
            }
          }
          createTablesOnStart = false
      }
    }
  //kafka{
  //  sasl.jaas.username = "admin"
 //   sasl.jaas.password = "admin-secret"
  //  ssl.truststore.password= "password"
 // }
}