shrine.hub.database.dataSourceFrom = "dataSourceConfig" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests, JNDI everywhere else
shrine.hub.database.dataSourceConfig.driverClassName = "com.mysql.cj.jdbc.Driver"
shrine.hub.database.dataSourceConfig.url = "jdbc:mysql://localhost:3306/HUB?serverTimezone=UTC"
shrine.hub.database.dataSourceConfig.credentials.username = "shrine"