shrine {

//  kafka{
//    sasl.jaas.username = "shrineNode1User"
//    sasl.jaas.password = "shrineNode1-secret"
//  }

    adapter {
        obfuscation {
            binSize = 6 //Round to the nearest binSize. Use 1 for no effect (to match SHRINE 1.21 and earlier).
            sigma = 6.5 //Noise to inject. Use 0 for no effect. (Use 1.33 to match SHRINE 1.21 and earlier).
            clamp = 10 //Maximum amount of noise to inject. (Use 3 to match SHRINE 1.21 and earlier).
            lowLimit = 10 //Anything below this will be reported as "lowLimit or fewer"
        }
    }
}//shrine
