shrine {

  // for local queue messaging system
  hub {
    create = true
    messagequeue {
      blockingqWebApi {
        enabled = true //todo remove when we have this disabled by default in our test systems
      }
    }
 }//hub
//  kafka{
//   sasl.jaas.username = "shrineHubUser"
//   sasl.jaas.password = "shrineHub-secret"
//  }
}//shrine
