shrine {
  adapter {
    query {
      database {
        dataSourceFrom = "JNDI" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests, JNDI everywhere else
        jndiDataSourceName = "java:comp/env/jdbc/adapter" //or leave out for tests
        createTablesOnStart = false //for testing with H2 in memory, when not running unit tests. Set to false normally
      }
    }
  }
}