#
# Configure the module for content.
#
# You MUST enable AuthType shibboleth for the module to process
# any requests, and there MUST be a require command as well. To
# enable Shibboleth but not specify any session/access requirements
# use "require shibboleth".
#

## Modified for i2b2 https://community.i2b2.org/wiki/pages/viewpage.action?pageId=55706050
<Location />
  AuthType shibboleth
  ShibRequestSetting requireSession 0
  require shibboleth
</Location>

#
# Configure the module for content.
#
# You MUST enable AuthType shibboleth for the module to process
# any requests, and there MUST be a require command as well. To
# enable Shibboleth but not specify any session/access requirements
# use "require shibboleth".
#

## Modified for i2b2 https://community.i2b2.org/wiki/pages/viewpage.action?pageId=55706050
<Location />
  AuthType shibboleth
  ShibRequestSetting requireSession 0
  require shibboleth
</Location>

<Location "/health">
    AuthType None
    Require all granted
    SetHandler server-status
</Location>