shrine{
    webclient {
        sessionTimeout="30 mins"
    }
    breakdownResultOutputTypes {
        PATIENT_AGE_COUNT_XML {
            description = "Demographic Distribution by Age"
            category = "Demographic"
        }

        PATIENT_RACE_COUNT_XML {
            description = "Demographic Distribution by Race"
            category = "Demographic"
        }

        PATIENT_VITALSTATUS_COUNT_XML {
            description = "Demographic Distribution by Vital Status"
            category = "Demographic"
        }

        PATIENT_GENDER_COUNT_XML {
            description = "Demographic Distribution by Sex"
            category = "Demographic"
        }
    }//breakdownResultOutputTypes
}