security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=oorg.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/usr/local/kafka/truststore/kafka-1/shrine.keystore
ssl.truststore.password=password
