#!/bin/bash

# change admin value if requried
CONFIGURE_PATH=/var/www/html/${CLIENT_TYPE}/i2b2_config_data.js
if [ "${CLIENT_TYPE}" = "admin" ]; then
  sed -i  "s|adminOnly: false|adminOnly: true|g" ${CONFIGURE_PATH}
fi

# rename Administration text
CONFIGURE_PATH=/var/www/html/${CLIENT_TYPE}/js-i2b2/cells/PM/PM_ctrlr.js
sed -i  "s|'Administrator'|'NextGen BMI Administrator'|g" ${CONFIGURE_PATH}

# To restrict directory acces the directory name (webclient/admin)
CONFIGURE_PATH=/etc/httpd/conf/httpd.conf
sed -i "s|client_type|$CLIENT_TYPE|g" ${CONFIGURE_PATH}
sed -i "s|.*ServerName.*|ServerName $SERVER_NAME|g" ${CONFIGURE_PATH}

# configure shibboleth xml
CONFIGURE_PATH=/etc/shibboleth/shibboleth2.xml
sed -i "s|<ApplicationDefaults entityID=.*|<ApplicationDefaults entityID=\"${SERVER_NAME}shibboleth\"|g" ${CONFIGURE_PATH}

