shrine.qep.database.dataSourceFrom = "dataSourceConfig" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests, JNDI everywhere else
shrine.qep.database.dataSourceConfig.driverClassName = "com.mysql.cj.jdbc.Driver"
shrine.qep.database.slickProfileClassName = "slick.jdbc.MySQLProfile$"
shrine.qep.database.dataSourceConfig.url = "jdbc:mysql://localhost:3306/QEP?serverTimezone=UTC"
shrine.qep.database.dataSourceConfig.credentials.username = "shrine"