rules = [
  "github:typelevel/cats-effect/v3_0_0?sha=v3.0.0"
  TypelevelUnusedIO
  TypelevelMapSequence
  TypelevelAs
  TypelevelUnusedShowInterpolator
  TypelevelFs2SyncCompiler
  TypelevelHttp4sLiteralsSyntax
]