<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<name>SHRINE</name>
	<groupId>net.shrine</groupId>
	<artifactId>shrine-base</artifactId>
	<packaging>pom</packaging>
	<version>4.4.0</version>
	<properties>
		<revision>4.4.0</revision>
		<changelist>-SNAPSHOT</changelist>
		<sha1/>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<scala-major-version>2.13</scala-major-version>
		<scala-version>2.13.12</scala-version>
		<java-major-version>17</java-major-version>

		<buildnumber-maven-plugin-version>3.2.0</buildnumber-maven-plugin-version>
		<flatten-maven-plugin-version>1.5.0</flatten-maven-plugin-version>
		<maven-antrun-version>3.1.0</maven-antrun-version>
		<maven-assembly-plugin-version>3.6.0</maven-assembly-plugin-version>
		<maven-compiler-version>3.11.0</maven-compiler-version>
		<maven-dependency-version>3.6.1</maven-dependency-version>
		<maven-exec-plugin-version>3.1.1</maven-exec-plugin-version>
		<maven-jar-plugin-version>3.3.0</maven-jar-plugin-version>
		<maven-plugin-annotations-version>3.10.2</maven-plugin-annotations-version>
		<maven-plugin-api-version>3.9.6</maven-plugin-api-version>
		<maven-plugin-plugin-version>3.10.2</maven-plugin-plugin-version>
		<maven-release-version>3.0.1</maven-release-version>
		<maven-resources-plugin-version>3.3.1</maven-resources-plugin-version>
		<maven-surefire-version>3.2.2</maven-surefire-version>
		<maven-war-plugin-version>3.4.0</maven-war-plugin-version>
		<scala-maven-plugin-version>3.4.6</scala-maven-plugin-version> <!-- todo changing to versions 4.0.0 through 4.8.1 breaks incremental mode and doubles the time for the compile. Don't bother upgrading until Bloop is available and reliable. SHRINE-3656 and SHRINE2020-557 -->

		<awssdk-version>2.21.37</awssdk-version>
		<cats-effect-testkit-version>3.5.3</cats-effect-testkit-version>
		<circe-config-version>0.10.1</circe-config-version>
		<circe-version>0.14.6</circe-version>
		<circe-extras-version>0.14.3</circe-extras-version>
		<courier-version>3.2.0</courier-version>
		<fs2-aws-version>6.1.0</fs2-aws-version>
		<fs2-kafka-version>3.2.0</fs2-kafka-version>
		<h2-version>2.2.224</h2-version>
		<http4s-jdk-http-client-version>0.9.1</http4s-jdk-http-client-version>
		<http4s-servlet-version>0.23.15</http4s-servlet-version> <!-- add back -Werror compiler arg with next version update -->
		<http4s-version>0.23.24</http4s-version>
		<junit-jupiter-version>5.10.1</junit-jupiter-version>
		<junit-version>4.13.2</junit-version>
		<logback-version>1.4.14</logback-version>
		<lucene-version>8.2.0</lucene-version> <!-- todo looks like a major API change - SHRINE2020-631 -->
		<mock-javamail-version>1.9</mock-javamail-version>
		<opencsv-version>5.9</opencsv-version>
		<scala-xml-version>2.2.0</scala-xml-version>
		<scalatest-version>3.0.8</scalatest-version> <!-- todo version 3.2.3 failed to compile - should matchers - SHRINE2020-663 -->
		<scopt-version>4.1.0</scopt-version>
		<servlet-api-version>4.0.1</servlet-api-version> <!-- todo maybe see https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api for new versions TODO JIRA ticket or fold in with tomcat 10-->
		<slf4j-version>2.0.9</slf4j-version>
		<slick-version>3.4.1</slick-version>
		<bouncy-castle-version>1.69</bouncy-castle-version>
	</properties>
	<!-- -->
	<modules>
		<module>adapter/adapter-exec</module>
		<module>commons/receiver</module>
		<module>adapter/adapter-in-j2ee</module>
		<module>apps/ping-app</module>
		<module>apps/ping-war</module>
		<module>hub/network-metrics-tool</module>
		<module>qep/researcher-metrics-tool</module>
		<module>hub/downstream-setup-tool</module>
		<module>adapter/service</module>
		<module>hub/network-lifecycle-tool</module>
		<module>qep/service</module>
		<module>qep/frontend</module>
		<module>apps/shrine-api-war</module>
		<module>apps/shrine-api-app</module>
		<module>hub/service</module>
		<module>ontology/service</module>
		<module>hub/message-service</module>
		<module>hub/data-store</module>
		<module>commons/util</module>
		<module>authz</module>
		<module>commons/auth</module>
		<module>commons/protocol</module>
		<module>shrine-setup</module>
		<module>ontology/lucene-indexer</module>
		<module>apps/mockcrc-app</module>
		<module>apps/mockcrc-war</module>
		<module>commons/http4s-client-test</module>
		<!-- <module>docker/scripts</module> -->
		<module>docker/custom-lifecycle</module>
	</modules>
	<!-- -->
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>io.github.evis</groupId>
					<artifactId>scalafix-maven-plugin_2.13</artifactId>
					<version>0.1.8_0.11.0</version>
					<configuration>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.typelevel</groupId>
							<artifactId>typelevel-scalafix_2.13</artifactId>
							<version>0.2.0</version>
						</dependency>
					</dependencies>
				</plugin>
				<plugin>
					<groupId>net.alchim31.maven</groupId>
					<artifactId>scala-maven-plugin</artifactId>
					<version>${scala-maven-plugin-version}</version>
                    <executions>
                        <!-- Allows Java and Scala code to be compiled together and call each other -->
                        <execution>
                            <id>compile</id>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <phase>compile</phase>
                        </execution>
                        <execution>
                            <id>test-compile</id>
                            <goals>
                                <goal>testCompile</goal>
                            </goals>
                            <phase>test-compile</phase>
                        </execution>
                        <execution>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                        </execution>
                    </executions>
					<configuration>
						<recompileMode>incremental</recompileMode>   <!-- this has no effect after shrine-maven-plugin 4.0.0 . See SHRINE-3656 -->
						<jvmArgs>
							<jvmArg>-Xms1024m</jvmArg>
							<jvmArg>-Xmx1024m</jvmArg>
						</jvmArgs>
						<scalaVersion>${scala-version}</scalaVersion>
						<args>
							<arg>-P:semanticdb:synthetics:on</arg>
							<arg>-Xcheckinit</arg>
							<arg>-unchecked</arg>
							<arg>-deprecation</arg>
							<arg>-feature</arg>
							<arg>-Xlint:adapted-args,inaccessible,infer-any,missing-interpolator,private-shadow,type-parameter-shadow</arg>
							<!--<arg>-Werror</arg>-->
							<arg>--explain-types</arg>
						</args>
						<compilerPlugins>
							<compilerPlugin>
								<groupId>org.scalameta</groupId>
								<artifactId>semanticdb-scalac_${scala-version}</artifactId>
								<version>4.8.14</version>
							</compilerPlugin>
						</compilerPlugins>
						<source>${java-major-version}</source>
                        <target>${java-major-version}</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-version}</version>
					<configuration>
						<source>${java-major-version}</source>
						<target>${java-major-version}</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>buildnumber-maven-plugin</artifactId>
					<version>${buildnumber-maven-plugin-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven-jar-plugin-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>${maven-resources-plugin-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>${maven-war-plugin-version}</version>
				</plugin>
				<!-- Ensure junit 5 jupiter tests run. Can be deleted when all the maven stack catches up, but the SHRINE 4.0-era stack will fail to run many unit tests -->
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven-surefire-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-antrun-plugin</artifactId>
					<version>${maven-antrun-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>${maven-assembly-plugin-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>${maven-dependency-version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-release-plugin</artifactId>
					<version>${maven-release-version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<!-- This creates .flattened-pom.xml files, and allows submudoles to be built
			     standalone using the ${revision}${sha1}${changelist} tags -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>${flatten-maven-plugin-version}</version>
				<configuration>
					<updatePomFile>true</updatePomFile>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
				</configuration>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- This creates properties ${timestamp} and ${buildNumber} (the SCM
				revision number) -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<shortRevisionLength>11</shortRevisionLength>
					<timestampFormat>yyyy-MM-dd HH:mm:ss</timestampFormat>
					<revisionOnScmFailure>(not available)</revisionOnScmFailure>
				</configuration>
			</plugin>
			<!-- Add versioning information to jars and wars -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
						<manifestEntries>
							<SCM-Revision>${buildNumber}</SCM-Revision>
							<SCM-Branch>${scmBranch}</SCM-Branch>
							<buildDate>${timestamp}</buildDate>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
						<manifestEntries>
							<SCM-Revision>${buildNumber}</SCM-Revision>
							<SCM-Branch>${scmBranch}</SCM-Branch>
							<buildDate>${timestamp}</buildDate>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<!-- -->
	<scm>
        <developerConnection>scm:git:https://open.catalyst.harvard.edu/stash/scm/shrine/shrine.git</developerConnection>
    </scm>
	<!-- -->
	<repositories>
		<!-- <repository> <id>CBMI-Nexus</id> <url>https://repo.open.catalyst.harvard.edu/nexus/content/groups/public/</url>
			<snapshots> <enabled>true</enabled> </snapshots> <releases> <enabled>true</enabled>
			</releases> </repository> -->
	</repositories>
	<!-- -->
	<pluginRepositories>
		<pluginRepository>
			<id>CBMI-Nexus</id>
			<url>https://repo.open.catalyst.harvard.edu/nexus/content/groups/public/</url>
		</pluginRepository>
	</pluginRepositories>
	<dependencies>
		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>${scala-version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j-version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit-jupiter-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit-jupiter-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>${junit-jupiter-version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-reflect</artifactId>
			<version>${scala-version}</version>
		</dependency>
	</dependencies>
	<!-- -->
	<distributionManagement>
		<snapshotRepository>
			<id>nexus</id>
			<name>Nexus Repo</name>
			<url>https://repo.open.catalyst.harvard.edu/nexus/content/repositories/snapshots</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
		<repository>
			<id>nexus</id>
			<name>Nexus Repo</name>
			<url>https://repo.open.catalyst.harvard.edu/nexus/content/repositories/releases</url>
		</repository>
	</distributionManagement>
</project>
