shrine {

  hub {
    messagequeue {
      //todo remove implementation when kafka code is updated
      implementation = "net.shrine.messagequeueclient.MessageQueueWebClient" //Fully-qualified class name of the MessaageQueueService to use
      blockingqWebApi {
        enabled = true // Why did I have to make this different than the develop branch? should it be in this referene.conf? or in a shrine.conf
      }
      blockingq {
        messageRedeliveryDelay = 45 seconds
        messageMaxDeliveryAttempts = 4
        messageTimeToLive = 4 days
        serverUrlPath = /shrine-api/mom
        waitTimeBeforeResent = 5 seconds
        receiveWaitTime = 50 seconds
      }
      httpClient {
        defaultTimeOut = 10 seconds
        tls.trustManager = "TrustAllCerts" // Should be "VerifyServerCerts", but can be "TrustAllCerts" to allow man-in-the-middle attacks
      }
    }
    allow500ExceptionEndpoints = false
  }
  aws {
    maxPrincipalsPerSqsPolicyStatement = 40 //50 is AWS' maximum. We picked 40 to leave some room to make a hub admin's bad night less bad
    //accessKeyId = "access key id" - must be in password.conf
    //secretAccessKey = "secret access key" - must be in password.conf
  }
  kafka {
    retries = 5
//  sasl.jaas.username =
//  sasl.jaas.password =
//  ssl.truststore.location =
//  ssl.truststore.password =
  }
}