shrine {
  qep {
    create = true

      collectQepAudit = true
      database {
        dataSourceFrom = "JNDI" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests, JNDI everywhere else
        jndiDataSourceName = "java:comp/env/jdbc/qep" //or leave out for tests
        //slickProfileClassName = "slick.jdbc.MySQLProfile$" // Can be
        //        slick.jdbc.H2Profile$
        //        slick.jdbc.MySQLProfile$
        //        slick.jdbc.PostgresProfile$
        //        slick.jdbc.SQLServerProfile$
        //        slick.jdbc.JdbcProfile
        //        slick.jdbc.OracleProfile$
        //        slick.jdbc.SQLServerProfile$
        //
        //        (Yes, with the $ on the end)
        // but will be inferred to a reasonable default via shrine's shrine.shrineDatabaseType property

        // For testing without JNDI
        //      dataSourceConfig {

        //typical test settings for unit tests
        //driverClassName = "org.h2.Driver"

        //url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;" //H2 embedded in-memory for unit tests
        //url = "jdbc:h2:~/stewardTest.h2;MODE=MySQL;" //H2 embedded on disk at ~/test
        //      }

        timeout = "30 seconds" //time to wait before db gives up, in seconds.
        createTablesOnStart = false //for testing with H2 in memory, when not running unit tests. Set to false normally
    }

    sendToHubAttempts = 3 //number of attempts to send a request to run a query to the hub before giving up and reporting a query in error

    attachSigningCert = true

    authenticationType = "pm" //can be none, or pm

    immediatelyRunIncomingQueries = true
  }
  webclient {
    //    domain = "foo" //name of the i2b2 PM cell domain used for login
    //    name  = "SHRINE"  //name of the i2b2 PM cell project used for login
    //    siteAdminEmail = "baz@example.com" //admin email address for this site
    bannerText = "SHRINE Network"
    termsOfUseText = """By accepting, "I acknowledge",
                       I agree to adhere to the terms of use
                       specified and aware that my usage may be audited.""""
    unauthorizedMessage = "You currently do not have access to SHRINE. Please contact your institution's SHRINE administrator for more information."
    usernameLabel = "User Name"     //text for the label displayed on login
    passwordLabel = "User Password" //text for the label displayed on login
    defaultNumberOfOntologyChildren = 10000 //huge default number of children to display in the ontology view
    queryFavingInstructions = "Here you can manage whether a query is a favorite or not. You can also edit the associated message." //text to guide use of the faving feature
    favingIconInstructions = "Make a query a favorite"
    nextStepsUrl = "https://enact-network.org/site-access-contacts/"
    helpLinks = {
      "Application Help": "https://open.catalyst.harvard.edu/wiki/display/SHRINE/SHRINE+4.4+Webclient+Help",
      "Network Help": "https://enact-network.org/site-access-contacts/"
    } //application help config.
//    ssoLinks = {
//          "Idp 1": "Idp Entity Id 1",
//          "Idp 2": "Idp Entity Id 2"
//    } //application sso Idp config.
  }

}
