shrine {
  hub {
    create = false //change to true to start a hub

    client {
      inProcessForTesting = "false"
      httpClientTimeOut = "10 seconds"
      tls.trustManager = "VerifyServerCerts" // Can be "TrustAllCerts" to allow man-in-the-middle attacks
    }
    mom {
      retryDelay = "5 seconds"
      momSendAttempts = 8 //Use 0 or fewer for no limit
    }
    result {
      overdueResultsCheckPeriod = "6 hours" //How often to check for overdue queries
      resultsOverdueAfter = "5 days" //If a result has not been updated in resultsOverdueAfter move it to error
      resultsDoNotBotherAfter = "30 days" //If a result is over resultsDoNotBotherAfter old then don't bother checking it to move it to error
      overdueResultsBatchSize = 100 //How big a batch to pull from the database at one go
    }
    database {
        dataSourceFrom = "JNDI" //Can be JNDI or dataSourceConfig . Use dataSourceConfig for command line tools and tests, JNDI everywhere else
        // relies on the existence of context.xml deployed in Tomcat's conf folder
        jndiDataSourceName = "java:comp/env/jdbc/hub" //or leave out for tests
        timeout = "30 seconds" //time to wait before db gives up, in seconds.
        createTablesOnStart = false
    }
  }
}