#!/bin/sh

INSTALL_HOME=`dirname $0`

CONFIG_FILE_DIR=${INSTALL_HOME}/conf

mkdir -p ${CONFIG_FILE_DIR}

CONFIG_CLASSPATH=.:${CONFIG_FILE_DIR}

LIB_DIR=${INSTALL_HOME}/lib

#
#Set up our classpath with our library dependencies...
for jar in `find ${LIB_DIR}/*.jar`;
do
    CONFIG_CLASSPATH=${jar}:${CONFIG_CLASSPATH}
done

#
#Guess JAVA_HOME if it's not set
if [ ${#JAVA_HOME} == 0 ]; then
    JAVA_HOME=/usr/local/java
fi

JVM_ARGS="-Xmx1024m -Dshrine.conf.file=/opt/shrine/tomcat/lib/shrine.conf"

java ${JVM_ARGS} -cp ${CONFIG_CLASSPATH} net.shrine.hub.setup.downstream.ShrineDownstreamSetup "$@"