<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>shrine-base</artifactId>
        <groupId>net.shrine</groupId>
        <version>4.4.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>shrine-api-app</artifactId>
    <name>SHRINE API App</name>
    <packaging>jar</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.http4s</groupId>
            <artifactId>http4s-dsl_${scala-major-version}</artifactId>
            <version>${http4s-version}</version>
        </dependency>
        <dependency>
            <groupId>org.http4s</groupId>
            <artifactId>http4s-core_${scala-major-version}</artifactId>
            <version>${http4s-version}</version>
        </dependency>
        <dependency>
            <groupId>org.http4s</groupId>
            <artifactId>http4s-server_${scala-major-version}</artifactId>
            <version>${http4s-version}</version>
        </dependency>
        <dependency>
            <groupId>org.http4s</groupId>
            <artifactId>http4s-servlet_${scala-major-version}</artifactId>
            <version>${http4s-servlet-version}</version>
        </dependency>
        <dependency>
            <groupId>org.http4s</groupId>
            <artifactId>http4s-client_${scala-major-version}</artifactId>
            <version>${http4s-version}</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${servlet-api-version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-receiver</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-adapter-in-j2ee</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-authz</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-ontology-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.shrine</groupId>
            <artifactId>shrine-util</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala-major-version}</artifactId>
            <version>${scalatest-version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
